# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='区域名')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标识名称')),
                ('title', models.CharField(max_length=200, verbose_name='主标题')),
                ('sub_title', models.CharField(max_length=600, verbose_name='副标题')),
                ('desp', models.TextField(blank=True, verbose_name='详细介绍')),
                ('av_area', models.ManyToManyField(null=True, to='yewu.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='人名')),
                ('head', models.CharField(max_length=300, verbose_name='头像')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号码')),
            ],
        ),
        migrations.CreateModel(
            name='SoldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='类型名称')),
                ('org_price', models.FloatField(blank=True, verbose_name='市场价')),
                ('price', models.FloatField(blank=True, verbose_name='价格')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yewu.Business', verbose_name='业务')),
            ],
        ),
    ]
