# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yewu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yewu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标识名称')),
                ('title', models.CharField(max_length=200, verbose_name='主标题')),
                ('sub_title', models.CharField(max_length=600, verbose_name='副标题')),
                ('desp', models.TextField(blank=True, verbose_name='详细介绍')),
                ('av_area', models.ManyToManyField(null=True, to='yewu.Area')),
            ],
        ),
        migrations.CreateModel(
            name='YewuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='业务分组')),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='av_area',
        ),
        migrations.AlterField(
            model_name='soldtype',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yewu.Yewu', verbose_name='业务'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.AddField(
            model_name='yewu',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yewu.YewuGroup', verbose_name='业务分组'),
        ),
    ]
