# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yewu', '0002_auto_20180915_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yewu',
            name='name',
        ),
        migrations.AlterField(
            model_name='yewu',
            name='av_area',
            field=models.ManyToManyField(to='yewu.Area', verbose_name='可用区域'),
        ),
    ]
