# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 20:47
from __future__ import unicode_literals

from django.db import migrations
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('yewu', '0003_auto_20180915_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldtype',
            old_name='bus',
            new_name='yewu',
        ),
        migrations.AddField(
            model_name='yewu',
            name='cover',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=200, verbose_name='封面'),
        ),
    ]
