# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 23:54
from __future__ import unicode_literals

from django.db import migrations
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('yewu', '0005_soldtype_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saler',
            name='head',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(max_length=300, verbose_name='头像'),
        ),
    ]
