# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('yewu', '0006_auto_20180917_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='saler',
            name='comment',
            field=models.CharField(blank=True, max_length=30, verbose_name='好评率'),
        ),
        migrations.AddField(
            model_name='saler',
            name='count',
            field=models.CharField(blank=True, max_length=30, verbose_name='最近接单'),
        ),
        migrations.AddField(
            model_name='saler',
            name='exp',
            field=models.CharField(blank=True, max_length=30, verbose_name='工作年限'),
        ),
        migrations.AddField(
            model_name='saler',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, verbose_name='业务员口号'),
        ),
        migrations.AlterField(
            model_name='saler',
            name='head',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='saler',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='手机号码'),
        ),
    ]
