# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yewu', '0008_freephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldtype',
            name='org_price',
            field=models.CharField(blank=True, max_length=100, verbose_name='市场价'),
        ),
        migrations.AlterField(
            model_name='soldtype',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='价格'),
        ),
    ]
