# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', helpers.director.model_func.cus_fields.cus_picture.PictureField(max_length=200, verbose_name='图片')),
                ('belong', models.IntegerField(choices=[(1, '主页'), (2, '工商')], default=1, verbose_name='从属于')),
                ('priority', models.IntegerField(default=0, help_text='越大，优先级越高', verbose_name='优先级')),
            ],
        ),
    ]
