# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='link',
            field=models.CharField(default='', max_length=500, verbose_name='链接'),
            preserve_default=False,
        ),
    ]
