# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yewu', '0002_auto_20180915_1731'),
        ('webpage', '0002_banners_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='显示名')),
                ('link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='yewu.Yewu', verbose_name='访问业务')),
            ],
        ),
        migrations.CreateModel(
            name='ActionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='显示名')),
                ('link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='yewu.Yewu', verbose_name='访问业务')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='显示名')),
                ('is_show', models.BooleanField(default=True, verbose_name='显示')),
            ],
        ),
    ]
