# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_action_actiongroup_mainmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.ActionGroup', verbose_name='链接组'),
        ),
    ]
