# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-15 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20180915_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiongroup',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.MainMenu', verbose_name='父级菜单'),
        ),
    ]
