# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_actiongroup_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='link',
            new_name='yewu',
        ),
        migrations.RenameField(
            model_name='actiongroup',
            old_name='link',
            new_name='yewu',
        ),
    ]
