# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20180916_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='高亮'),
        ),
    ]
