# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('yewu', '0006_auto_20180917_2354'),
        ('webpage', '0009_action_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='YewuRecomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='大标题')),
                ('sub_title', models.CharField(max_length=300, verbose_name='小标题')),
                ('price', models.CharField(max_length=30, verbose_name='价格')),
                ('cover', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=200, verbose_name='宣传图片')),
            ],
        ),
        migrations.CreateModel(
            name='YewuRecomPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='大标题')),
                ('sub_title', models.CharField(max_length=300, verbose_name='小标题')),
                ('belong', models.IntegerField(choices=[(1, '主页'), (2, '工商')], default=1, verbose_name='显示页面')),
                ('priority', models.IntegerField(default=0, help_text='越大，优先级越高', verbose_name='优先级')),
            ],
        ),
        migrations.AlterField(
            model_name='banners',
            name='belong',
            field=models.IntegerField(choices=[(1, '主页'), (2, '工商')], default=1, verbose_name='显示页面'),
        ),
        migrations.AddField(
            model_name='yewurecomitem',
            name='recom_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.YewuRecomPanel', verbose_name='从属于'),
        ),
        migrations.AddField(
            model_name='yewurecomitem',
            name='yewu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yewu.Yewu', verbose_name='展示业务'),
        ),
    ]
