# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_auto_20180917_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='链接组')),
                ('links', models.TextField(verbose_name='链接项')),
            ],
        ),
        migrations.CreateModel(
            name='RichPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='表示名')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('createtime', models.DateField(verbose_name='创建日期')),
                ('brow_count', models.CharField(max_length=100, verbose_name='浏览量')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='链接')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
