# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_footerlink_richpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richpage',
            name='link',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='richpage',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='标识名'),
        ),
    ]
