# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 23:57
from __future__ import unicode_literals

from django.db import migrations
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_auto_20180926_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='icon',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='图标'),
        ),
    ]
