# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-28 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_mainmenu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='icon',
            field=models.CharField(blank=True, help_text='请填写font-awesome图标名称', max_length=300, verbose_name='图标'),
        ),
    ]
