# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_auto_20181028_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='icon',
            field=models.CharField(blank=True, help_text='请填写html图片代码,例如font awesome代码', max_length=300, verbose_name='图标'),
        ),
    ]
